---
title: <div align="center"> HW1 Exercise 2 - Financial Analyis 
author: <div align="center"> 
   Nathalie Mayor
  - Giovanni Magagnin
  - Florent Idargo
  - Alexandre Guerra
date: "3/3/2020"
output: html_document
---

```{r,echo=FALSE,results='hide',error=FALSE,message=FALSE,warning=FALSE}

quantmod::getSymbols(c("VALE","INTC","WFC","CSCO"),src="yahoo", from="2019-01-01")
```

<div align="center">
```{r,echo=FALSE}
stocks <- list(VALE[,4],INTC[,4],WFC[,4],CSCO[,4])
par(mfrow= c(2,2))
titres <- list("VALE", "INTC", "WFC","CSCO")

for (i in 1:4) {
  #titre <- stocks[[1]][0]
  leGraph <- plot(stocks[[i]],main = titres[i])
  print(leGraph)
}


```


```{r,echo=FALSE,results="hide",error=FALSE,message=FALSE,warning=FALSE}
library(quantmod)


### 4 CANDLES

today<-Sys.Date()
four_months_ago <- seq(today, length = 2, by = "-4 months")[2]
```

```{r,echo=FALSE,results='hide',error=FALSE,message=FALSE,warning=FALSE}
getSymbols(c("VALE","INTC","WFC","CSCO"),src="yahoo", from=four_months_ago)
```

```{r,echo=FALSE,warning=FALSE}
candleChart(VALE, theme = 'white', type = 'candles',main='sdas')

candleChart(INTC, theme = 'white', type = 'candles')

candleChart(WFC, theme = 'white', type = 'candles')

candleChart(CSCO, theme = 'white', type = 'candles')
```
<div align="justify">

```{r,echo=FALSE,warning=FALSE}
### 5 MEAN AND VAR OF TS

(ten_years_ago<-seq(today, length = 2, by = "-10 years")[2])
paste("The ten years ago date is:", toString(ten_years_ago),sep=" ")
```

```{r,echo=FALSE,results='hide',error=FALSE,message=FALSE,warning=FALSE}
getSymbols(c("VALE","INTC","WFC","CSCO"),src="yahoo", from=ten_years_ago)
```

```{r,echo=F}

VALE_returns <- na.omit(ClCl(VALE[,4]))
mean_VALE<-mean(VALE_returns)
var_VALE<-var(VALE_returns)
paste("The mean daily return since VALE's inception is:", toString(mean_VALE),sep=" ")
paste("The mean daily variance since VALE's inception is:", toString(var_VALE),sep=" ")
paste("As an indicative value, the mean daily volatility since VALE's inception is:", toString(sqrt(var_VALE)))


INTC_returns <- na.omit(ClCl(INTC[,4]))
mean_INTC <- mean(INTC_returns)
var_INTC <- var(INTC_returns)
paste("The mean daily return over ten years of INTC is:", toString(mean_INTC),sep=" ")
paste("The mean daily variance  over ten years of INTC is:", toString(var_INTC),sep=" ")
paste("As an indicative value, the mean daily volatility since INTC's inception is:", toString(sqrt(var_INTC)))

WFC_returns <- na.omit(ClCl(WFC[,4]))
mean_WFC <- mean(WFC_returns)
var_WFC <- var(WFC_returns)
paste("The mean daily return over ten years of INTC is:", toString(mean_WFC),sep=" ")
paste("The mean daily variance over ten years of INTC is:", toString(var_WFC),sep=" ")
paste("As an indicative value, the mean daily volatility since WFC's inception is:", toString(sqrt(var_WFC)))

CSCO_returns <- na.omit(ClCl(CSCO[,4]))
mean_CSCO <- mean(CSCO_returns)
var_CSCO <- var(CSCO_returns)
paste("The mean daily return over ten years of INTC is:", toString(mean_CSCO),sep=" ")
paste("The mean daily variance over ten years of INTC is:", toString(var_CSCO),sep=" ")
paste("As an indicative value, the mean daily volatility from the ten past years of CSCO is:", toString(sqrt(var_CSCO)))

### 6


DRV<-dailyReturn(VALE[,4])
DailySharpeV<-mean(DRV-0.03/252)/sd(DRV)
AnnualSharpeV<-DailySharpeV*sqrt(252)
paste("The sharpe ratio of VALE is:", toString(AnnualSharpeV),sep=" ")


DRI<-dailyReturn(INTC[,4])
DailySharpeI<-mean(DRI-0.03/252)/sd(DRI)
AnnualSharpeI<-DailySharpeI*sqrt(252)
paste("The sharpe ratio of INTC is:", toString(AnnualSharpeI),sep=" ")

DRW<-dailyReturn(WFC[,4])
DailySharpeW<-mean(DRW-0.03/252)/sd(DRW)
AnnualSharpeW<-DailySharpeW*sqrt(252)
paste("The sharpe ratio of WRC is:", toString(AnnualSharpeW),sep=" ")

DRC<-dailyReturn(CSCO[,4])
DailySharpeC<-mean(DRC-0.03/252)/sd(DRC)
AnnualSharpeC<-DailySharpeC*sqrt(252)
paste("The sharpe ratio of CSCO is:", toString(AnnualSharpeC),sep=" ")

```
### Question 7
```{r,warning=FALSE,error=FALSE,message=FALSE}

#####7
quantmod::getSymbols(c("VALE","INTC","CSCO","WFC"),src="yahoo", from="2010-01-01")
stocks <- list(VALE[,4],INTC[,4],CSCO[,4],WFC[,4])
cumulated_var <- 0

historique <- data.frame(vale_returns = ClCl(VALE[,4]),intc_returns = ClCl(INTC[,4]),csco_returns = ClCl(CSCO[,4]),wfc_returns = ClCl(WFC[,4]))
historique <- historique[-1,]

#Variance of the portofolio
covariance_matrix <- matrix(cov(historique),ncol=4,nrow=4)
weight_matrix <- matrix(rep(0.25,4),ncol=1,nrow=4)
weight_matrix_transpose <- matrix(rep(0.25,4),ncol=4,nrow=1)

variance_equally_weighted_portofolio <- weight_matrix_transpose %*% covariance_matrix %*% weight_matrix
paste("The variance of the return of an equally weighted portofolio built of these four stocks is:", toString(round(variance_equally_weighted_portofolio,digits=6)), "and the volatility is:", toString(round(sqrt(variance_equally_weighted_portofolio),digit=5)), sep=" ")

#single stocks average var

for (stock in historique) {
  cumulated_var <- cumulated_var + var(stock)
}
average_var_single_stock_portofolio = cumulated_var/4

paste("The average variance of a portofolio made of 100% of one of these stocks is:", toString(round((cumulated_var/4),digits=5)), "and its average volatility would therefore be:",toString(round(sqrt((cumulated_var/4)),digits=5)))
```
We therefore observe that the volatility and variance of a single stock portofolio is consistently superior to the 4 equally weighted assets portofolio and has an approximately `r round((average_var_single_stock_portofolio/variance_equally_weighted_portofolio),digits=2)` higher variance. This clearly unerline the benefits from diversification.







